sudo: false
language: cpp
compiler:
  - g++
  - clang++
cache: apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - g++-4.8
      - clang-3.8
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
script: ./build.sh
