sudo: false
language: cpp
compiler:
  - clang++
  - g++
cache: apt
addons:
  apt:
    packages:
      - g++-5
      - clang-3.8
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang-3.8"; fi
script: ./build.sh
